# Generated by Django 2.0.5 on 2018-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regNlog', '0003_person_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='匿名用户', max_length=30)),
                ('userphoto', models.ImageField(default='images/q1.png', upload_to='imgs')),
                ('followusername', models.CharField(max_length=30)),
            ],
        ),
    ]
