# Generated by Django 2.0.5 on 2018-06-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regNlog', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.AddField(
            model_name='person',
            name='follow',
            field=models.ManyToManyField(related_name='fans', to='regNlog.Person'),
        ),
    ]
