# Generated by Django 2.0.5 on 2018-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regNlog', '0005_auto_20180619_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userphoto',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
    ]
