# Generated by Django 2.0.5 on 2018-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regNlog', '0006_auto_20180619_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userphoto',
            field=models.ImageField(default='imgs/q1.png', upload_to=''),
        ),
    ]
