# Generated by Django 2.0.5 on 2018-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regNlog', '0007_auto_20180622_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userphoto',
            field=models.ImageField(default='q1.png', upload_to=''),
        ),
    ]
