# Generated by Django 2.0.5 on 2018-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20180530_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
