# Generated by Django 2.0.5 on 2018-06-15 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_article_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('username', models.CharField(default='user', max_length=30)),
                ('collectuser', models.CharField(default='user', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('username', models.CharField(default='user', max_length=30)),
                ('likeuser', models.CharField(default='user', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='relative',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='mandajc￥', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='tag2',
            field=models.CharField(default='mandajc￥', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='tag3',
            field=models.CharField(default='mandajc￥', max_length=50),
        ),
    ]
