# Generated by Django 2.0.5 on 2018-06-15 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20180615_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('username', models.CharField(default='user', max_length=30)),
                ('comment', models.TextField(default='评论待编辑...')),
                ('userphoto', models.ImageField(default='images/q1.png', upload_to='imgs')),
                ('commentuser', models.CharField(default='user', max_length=30)),
                ('nickname', models.CharField(default='匿名', max_length=30)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='like',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='collect',
            name='collectuser',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='collect',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeuser',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
