# Generated by Django 2.0.5 on 2018-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_auto_20180615_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='articleId',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='title',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='username',
        ),
        migrations.AddField(
            model_name='collect',
            name='article',
            field=models.ManyToManyField(related_name='collect_article', to='Article.Article'),
        ),
    ]
