# Generated by Django 2.0.5 on 2018-06-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20180616_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
