# Generated by Django 2.0.5 on 2018-06-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_auto_20180616_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdate']},
        ),
    ]
