# Generated by Django 2.0.5 on 2018-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20180619_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo1',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo2',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo3',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='userphoto',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
    ]
