# Generated by Django 2.0.5 on 2018-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_auto_20180619_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo1',
            field=models.ImageField(default='imgs/q1.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo2',
            field=models.ImageField(default='imgs/q1.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo3',
            field=models.ImageField(default='imgs/q1.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='userphoto',
            field=models.ImageField(default='imgs/q1.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userphoto',
            field=models.ImageField(default='images/q1.png', upload_to=''),
        ),
    ]
