"""
Django settings for iFairyServer project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import pymysql  
pymysql.install_as_MySQLdb()  

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import qiniu

QINIU_ACCESS_KEY='0jScFLqK3lAuyrxrszk4LiZ6H_iXsRMi03NL-I5-'
QINIU_SECRET_KEY='802q-qCQX4VCMrylVvEM2OVWd56sAvbCVDyI9Wuq'
QINIU_BUCKET_NAME='mandajc'
QINIU_BUCKET_DOMAIN='papfvr9g2.bkt.clouddn.com'
QINIU_SECURE_URL = False      #使用http
PREFIX_URL = 'http://'
#参考，按照上面的复制即可https://blog.csdn.net/twilight041132/article/details/50570807
# ROOT_URL = '/'
# MEDIA_URL = ROOT_URL + 'res/images/'
#Media
MEDIA_ROOT = '/res/images/'
MEDIA_URL = PREFIX_URL + QINIU_BUCKET_DOMAIN + '/res/images/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'
#静态文件
# STATIC_URL = QINIU_BUCKET_DOMAIN + '/static/'
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
STATIC_ROOT = BASE_DIR + '/res/static/'
STATIC_URL = QINIU_BUCKET_DOMAIN + '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'res/'),
# )
# STATIC_ROOT = os.path.join(BASE_DIR, 'res/images')
STATICFILES_STORAGE = 'qiniustorage.backends.QiniuStaticStorage'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
   'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dbwgwyu*1qzou1$*3cd3+p4+gciq-**09zex-&xxc+ij_ud899'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['203.195.206.214', '192.168.1.104', '192.168.199.209', '172.19.89.112', '127.0.0.1','mandajc.xicp.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'regNlog',
    'Article',
    'Column',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iFairyServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iFairyServer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ifairyserver',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'jkl;',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'
# LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
#api访问图片的关键！！！
#参考，按照上面的复制即可https://blog.csdn.net/twilight041132/article/details/50570807
# MEDIA_ROOT = BASE_DIR + '/res/images/'
# ROOT_URL = '/'
# MEDIA_URL = ROOT_URL + 'res/images/'
# STATIC_URL = '/res/'
# STATICFILES_DIRS = (
# os.path.join(BASE_DIR, 'res'),
# )