# Generated by Django 2.0.5 on 2018-06-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('content', models.TextField(default='文档待编辑...')),
                ('tag', models.CharField(default='美白', max_length=50)),
                ('likenum', models.IntegerField(default=0)),
                ('dislikenum', models.IntegerField(default=0)),
                ('username', models.CharField(default='user', max_length=30)),
                ('nickname', models.CharField(default='匿名', max_length=30)),
                ('userphoto', models.ImageField(default='images/q1.png', upload_to='imgs')),
                ('photo1', models.ImageField(default='images/q1.png', upload_to='imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnId', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('username', models.CharField(default='user', max_length=30)),
                ('dislikeuser', models.CharField(default='user', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnId', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('username', models.CharField(default='user', max_length=30)),
                ('likeuser', models.CharField(default='user', max_length=30)),
            ],
        ),
    ]
