# Generated by Django 2.0.5 on 2018-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Column', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='photo1',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='column',
            name='userphoto',
            field=models.ImageField(default='imgs/q1.png', upload_to='imgs'),
        ),
    ]
